# Generated by Django 6.0.5 on 2026-06-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_pfp.png', upload_to='profile_avatrs'),
        ),
    ]
