# Generated by Django 6.0.6 on 2026-06-13 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_movie_id_alter_profile_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('score', models.IntegerField()),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='game_sessions',
                    to=settings.AUTH_USER_MODEL
                    )),
            ],
            options={
                'ordering': ['-date_played'],
            },
        ),
    ]
