# Generated by Django 6.0.6 on 2026-06-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gamesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='endless_mode',
            field=models.BooleanField(default=False),
        ),
    ]
